### ISSUE TITLE
Loading issues

### ISSUE THREAD

**Issue by Perksey** [mellinoe/ge#7]
First of all, the submodules are a tad messed up, so this creates a bunch of errors.
Secondly, are we gonna get an sln file at any point? ;)
If not, please send me a ZIP file of your local working dir, as I just can't get the repo working on my PC.

Thanks in advance,

Dylan.

**Comment by mellinoe** [comment]
Hey Dylan, perhaps you'd have more luck cloning the [CrazyCore](https://github.com/mellinoe/CrazyCore/) repository. I fixed the submodule links up a few months ago, so as far as I know they should still be okay. What sorts of issues are you seeing?

There's a solution file over in that repository as well, which includes the relevant projects.

**Comment by Perksey** [comment]
I'm using JetBrains Rider - which is fantastic btw.

I've cloned CrazyCore, but I've been greeted with 2535 errors.
https://gyazo.com/7d13de4a7a1614ad20ae8741386859cb

Most of them live in the Veldrid submodule, but there are a fair few errors in the Editor, Engine and the game itself.

Try it - clone the repository clean and try fire up the VS solution.

**Comment by mellinoe** [comment]
Ah, I see what happened. We fixed up the submodule link for Veldrid in the last PR, but we didn't actually update CrazyCore to point at it. I did that just now with the latest commit. I'm out of town, so I'm not in the best place to test whether everything works as expected, however.

**Comment by Perksey** [comment]
Alright, will try it out later. :)

**Comment by mellinoe** [comment]
I think everything is working now.
