### ISSUE TITLE
Missing ImageSharp.dll

### ISSUE THREAD

**Issue by lokimeyburg** [mellinoe/ge#8]
When compiling CrazyCore, I get a `warning` from the game engine:

```
/usr/local/share/dotnet/sdk/2.1.300/Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3106: Assembly strong name "../../ext/veldrid/bin/ImageSharp/netstandard1.3/ImageSharp.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\). [/CrazyCore/code/ge/src/Engine.Launcher/Engine.Launcher.csproj]
/usr/local/share/dotnet/sdk/2.1.300/Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3106: Assembly strong name "../../ext/veldrid/bin/ImageSharp/netstandard1.3/ImageSharp.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\). [/CrazyCore/code/ge/src/Engine.Launcher/Engine.Launcher.csproj]
```

It appears that these two files are referencing `ext/veldrid/bin/ImageSharp` which does not exist.

```
/src/Editor/Editor.csproj#L133
/src/Engine.Launcher/Engine.Launcher.csproj#L70
```

I've looked at Veldrid Legacy and compiled it myself, but for the life of me, I don't see ImageSharp anywhere.

**Comment by mellinoe** [comment]
Yeah, that's a problem. Unfortunately, the version of ImageSharp used in here has since been removed from MyGet. It would be a decent chunk of work to update the (extremely old) version of Veldrid used here onto the latest version of ImageSharp.

**Comment by mellinoe** [comment]
Actually, I've forgotten that I already did the update to ImageSharp. There's just a couple of erroneous references left in the project file that I forgot to remove after debugging. I pushed a couple more commits that fix things up in that regard.
